name: Bug report
description: open a bug report.
title: "[Bug]:"
labels: ["bug"]
projects: ["tinteeam/gregtech-pack-forge-issue-tracker"]
assignees: 
  - randomusert
body:
  - type: markdown
    attributes:
      value: |
        Please fill this bug report!
  - type: textarea
    id: what-happened
    attributes:
       label: What happened?
       description: what did you expect?
       value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
       label: what version of the modpack are you playing
       description: version
       value: "0.1.0"
    validations:
      required: true
